-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgpkRzywH/hK3DVGWn
1xzCMbnh7YXA/g58vV/25bOpW8WgCgYIKoZIzj0DAQehRANCAASlCqhq6/H7Y+Zu
gNUuGzp3KvEl/brzd2vqyhPgg4tK0HXzWYvFr0I5R8BfpgauW2Jn/UtBbqYs9Ni0
JPiAUQCT
-----END PRIVATE KEY-----